.TH open 1
.SH NAME
open \- open file or URL with X applications
.SH SYNOPSIS
.B open
.RB [ \-c
.IR mimefile ]
.IR file
.SH DESCRIPTION
.B open
opens a file or URL with the X application specified in the mimefile.
The mimefile is a file set by the option
.B -c
or by the environment variable
.B MIMEFILE
.PP
The options are as follows:
.TP
.BI \-c " mimefile"
Use
.I mimefile
as the configuration file.  This option overrides the
.B MIMEFILE
environment variable.
.PP
The mimefile is a text file containing rules for opening files by mimetype or extensions.
.PP
Each line in the mimefile is a rule.
A rule is composed by a mimetype or a file extension followed by a colon
.RB ( : ),
followed by the command that opens a file with that mimetype or extension.
Whitespace around the colon is ignored.
.PP
In the mimefile, extensions have preference over mimetypes.
That is, if a file's both extension and mimetype are specified in the mimefile,
then the extension is read and the mimetype is ignored.
.PP
Mimetypes and extensions in the mimefile are subject to globbing,
that is, an asterisk
.RB ( * )
matches any character in any number.  Note that globbing is not regular expression
(globbing is the same expression used by the shell to match files).
Mimetypes and extensions can occur on the same rule separated by a vertical line
.RB ( | )
.PP
In the mimefile, the command that opens a file can contain environment
variables.
.PP
Comments begins with
.B #
and spans until the end of line.
.SH ENVIRONMENT
The following environment variables affect the execution of
.B open
.TP
.B MIMEFILE
File that contains rules describing which application to open each file or url.
.SH EXIT STATUS
.TP
.B 0
Success.
.TP
.B >0
Error occurred.
.SH EXAMPLES
The following is an example of a mimefile.
Note that the rule for the mimetype
.B text/html
needs to come before the rule for
.B text/*
because the rules are matched in order.
.IP
.EX
# web
text/html:  firefox

# text
text/*:           urxvt -e $EDITOR
inode/x-empty:    urxvt -e $EDITOR
inode/directory:  urxvt -e fm

# Docs
application/pdf:        zathura
application/postscript: zathura
application/epub*:      zathura
image/*djvu:            zathura

# media
mkv|mp4|avi: mpv
image/*:     sxiv
audio/*:     qmmp
.EE
.PP
Note also how patterns are used with the
.B *
and the
.B |
characters.
.PP
The following is an example of how to open a file with open.
The environment variable
.B MIMEFILE
needs to be set before running it.
.IP
.EX
$ open /tmp/file.jpg
.EE
